//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServerWorker.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ServerWorker.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @echo off
        ///rem
        ///rem Get build type from argument list
        ///    if &quot;%1&quot; == &quot;debug&quot;   goto SetBuildType
        ///    if &quot;%1&quot; == &quot;release&quot; goto SetBuildType
        ///    if &quot;%1&quot; == &quot;i4dbg&quot;   goto SetBuildType
        ///    if &quot;%1&quot; == &quot;i4rel&quot;   goto SetBuildType
        ///    if &quot;%1&quot; == &quot;&quot;        goto SetDefaultBuildType
        ///    echo &quot;%0: Unknown build type %1&quot;
        ///    set build_type=release
        ///    echo &quot; Build type set to %build_type%&quot;
        ///    goto BuildTypeDone
        ///:SetBuildType
        ///    set build_type=%1
        ///    goto BuildTypeDone
        ///:SetDefaultBuildType
        ///    set buil [rest of string was truncated]&quot;;.
        /// </summary>
        public static string solver10_0 {
            get {
                return ResourceManager.GetString("solver10_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @echo off
        ///rem
        ///rem Get build type from argument list
        ///    if &quot;%1&quot; == &quot;debug&quot;   goto SetBuildType
        ///    if &quot;%1&quot; == &quot;release&quot; goto SetBuildType
        ///    if &quot;%1&quot; == &quot;i4dbg&quot;   goto SetBuildType
        ///    if &quot;%1&quot; == &quot;i4rel&quot;   goto SetBuildType
        ///    if &quot;%1&quot; == &quot;&quot;        goto SetDefaultBuildType
        ///    echo &quot;%0: Unknown build type %1&quot;
        ///    set build_type=release
        ///    echo &quot; Build type set to %build_type%&quot;
        ///    goto BuildTypeDone
        ///:SetBuildType
        ///    set build_type=%1
        ///    goto BuildTypeDone
        ///:SetDefaultBuildType
        ///    set buil [rest of string was truncated]&quot;;.
        /// </summary>
        public static string solver10_1 {
            get {
                return ResourceManager.GetString("solver10_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @echo off
        ///rem
        ///rem Get build type from argument list
        ///    if &quot;%1&quot; == &quot;debug&quot;   goto SetBuildType
        ///    if &quot;%1&quot; == &quot;release&quot; goto SetBuildType
        ///    if &quot;%1&quot; == &quot;i4dbg&quot;   goto SetBuildType
        ///    if &quot;%1&quot; == &quot;i4rel&quot;   goto SetBuildType
        ///    if &quot;%1&quot; == &quot;&quot;        goto SetDefaultBuildType
        ///    echo &quot;%0: Unknown build type %1&quot;
        ///    set build_type=release
        ///    echo &quot; Build type set to %build_type%&quot;
        ///    goto BuildTypeDone
        ///:SetBuildType
        ///    set build_type=%1
        ///    goto BuildTypeDone
        ///:SetDefaultBuildType
        ///    set buil [rest of string was truncated]&quot;;.
        /// </summary>
        public static string solverDEV_0 {
            get {
                return ResourceManager.GetString("solverDEV_0", resourceCulture);
            }
        }
    }
}
